# Generated by Django 5.1.3 on 2024-12-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='region_sigungo',
            new_name='region_sigungu',
        ),
    ]
